# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b1226bf19d13da3dda9417253b2547567babeda8b85e7bf9d0a0181401ce8a1d934b5f1ecb9c6799d80a5acf68e325f6ceccf876efa417ca1de44eefd69746

test:
  secret_key_base: f99b4085c647ec6a7045ac94edc24b0dcfd62f049bfc1ef69eecf14910e5367292a97025286f231251513a3e34a9e34a6a114fc05ae07c59ec32902b94f7765e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
